; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[platformio]
;	default_envs = m5stack-core2 
default_envs = m5stack-core2-sdu 
; default_envs = m5stack-cores3 

[env]
platform = espressif32
framework = arduino
upload_speed = 1500000
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
build_type = release
;board_build.filesystem = spiffs
;lib_ldf_mode = deep

build_flags=
	-DBOARD_HAS_PSRAM
  -Wno-deprecated-declarations
  -Wno-cpp

lib_deps =
    https://github.com/me-no-dev/AsyncTCP
    https://github.com/me-no-dev/ESPAsyncWebServer
    m5stack/M5Unified

[sd-updater]
build_flags=
    -DENABLE_SD_UPDATER
lib_deps = 
	tobozo/M5Stack-SD-Updater
	; https://github.com/tobozo/ESP32-targz



[env:m5stack-core2]
;-- Core2 v1.0/v1.1/AWS --
board = m5stack-core2



[env:m5stack-core2-sdu]
;-- Core2 v1.0/AWS -- excluding v1.1
extends = env:m5stack-core2, sd-updater
board_build.partitions = default_16MB.csv
build_flags = ${env:m5stack-core2.build_flags} ${sd-updater.build_flags}
lib_deps = ${env:m5stack-core2.lib_deps} ${sd-updater.lib_deps}



[env:m5stack-cores3]
;-- CoreS3/SE --
board = m5stack-cores3
board_build.arduino.memory_type = qio_qspi ; この行を指定しないとCoreS3では動かない

